const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const CLAUSES = [
  // Clause 4: Context of the Organization
  { number: "4", title: "Context of the Organization", level: 0, description: "Understanding the organization and its context is the foundation of the ISMS. This clause requires you to determine external and internal issues relevant to the organization's purpose and that affect its ability to achieve the intended outcomes of its ISMS.", guidance: "Start by identifying what your organization does, who your stakeholders are, and what internal/external factors could impact your information security. Consider regulatory requirements, business objectives, and the threat landscape." },
  { number: "4.1", title: "Understanding the Organization and its Context", level: 1, parent: "4", description: "The organization shall determine external and internal issues that are relevant to its purpose and that affect its ability to achieve the intended outcome(s) of its information security management system.", guidance: "Conduct a PESTLE analysis (Political, Economic, Social, Technological, Legal, Environmental) for external issues. For internal issues, consider organizational culture, governance, resources, knowledge, and capabilities. Document these in a context analysis document." },
  { number: "4.2", title: "Understanding the Needs and Expectations of Interested Parties", level: 1, parent: "4", description: "The organization shall determine: a) interested parties that are relevant to the ISMS; b) the relevant requirements of these interested parties; c) which of these requirements will be addressed through the ISMS.", guidance: "Create a stakeholder register listing all interested parties (customers, regulators, employees, suppliers, etc.), their requirements, and how your ISMS addresses them. Include legal/regulatory requirements, contractual obligations, and voluntary commitments." },
  { number: "4.3", title: "Determining the Scope of the ISMS", level: 1, parent: "4", description: "The organization shall determine the boundaries and applicability of the ISMS to establish its scope. When determining this scope, the organization shall consider: a) the external and internal issues referred to in 4.1; b) the requirements referred to in 4.2; c) interfaces and dependencies between activities performed by the organization, and those that are performed by other organizations.", guidance: "Define clear boundaries: which locations, departments, processes, and information systems are included. Document the scope statement clearly - auditors will verify this first. The scope should be realistic and achievable." },
  { number: "4.4", title: "Information Security Management System", level: 1, parent: "4", description: "The organization shall establish, implement, maintain and continually improve an information security management system, including the processes needed and their interactions, in accordance with the requirements of this document.", guidance: "This is the overarching requirement to have an ISMS. Document how your ISMS processes interact, from risk assessment to control implementation to monitoring. Create an ISMS process map." },

  // Clause 5: Leadership
  { number: "5", title: "Leadership", level: 0, description: "Top management must demonstrate leadership and commitment to the ISMS. This clause ensures that information security is integrated into business processes and that adequate resources are available.", guidance: "Leadership commitment is not just a formality - auditors will interview top management. Ensure leaders understand and can articulate their role in information security." },
  { number: "5.1", title: "Leadership and Commitment", level: 1, parent: "5", description: "Top management shall demonstrate leadership and commitment with respect to the ISMS by: ensuring the information security policy and objectives are established and compatible with the strategic direction; ensuring integration of ISMS requirements into business processes; ensuring resources are available; communicating the importance of effective information security management; ensuring the ISMS achieves its intended outcomes; directing and supporting persons to contribute to effectiveness; promoting continual improvement; supporting other relevant management roles.", guidance: "Evidence includes: minutes from management review meetings, signed policies, budget allocations for security, management communications about security, and integration of security into business planning." },
  { number: "5.2", title: "Policy", level: 1, parent: "5", description: "Top management shall establish an information security policy that: is appropriate to the purpose of the organization; includes information security objectives or provides the framework for setting them; includes a commitment to satisfy applicable requirements; includes a commitment to continual improvement. The policy shall be available as documented information, communicated within the organization, and available to interested parties as appropriate.", guidance: "The policy should be concise (1-2 pages), signed by top management, and reviewed annually. It must be communicated to all employees and relevant external parties. Avoid generic templates - tailor it to your organization." },
  { number: "5.3", title: "Organizational Roles, Responsibilities and Authorities", level: 1, parent: "5", description: "Top management shall ensure that the responsibilities and authorities for roles relevant to information security are assigned and communicated. Top management shall assign the responsibility and authority for: ensuring that the ISMS conforms to the requirements of ISO 27001; reporting on the performance of the ISMS to top management.", guidance: "Create an RACI matrix for ISMS activities. Define roles such as CISO, Information Security Manager, Risk Owners, Asset Owners. Document in job descriptions and organizational charts." },

  // Clause 6: Planning
  { number: "6", title: "Planning", level: 0, description: "Planning addresses risks and opportunities, information security objectives, and how to achieve them. This is where you identify what could go wrong and plan how to handle it.", guidance: "This clause is critical for certification. Your risk assessment methodology and risk treatment plan are core ISMS documents that auditors scrutinize heavily." },
  { number: "6.1", title: "Actions to Address Risks and Opportunities", level: 1, parent: "6", description: "When planning for the ISMS, the organization shall consider the issues referred to in 4.1 and the requirements referred to in 4.2 and determine the risks and opportunities that need to be addressed to: ensure the ISMS can achieve its intended outcomes; prevent or reduce undesired effects; achieve continual improvement.", guidance: "Develop a formal risk assessment methodology. Use a risk register to document all identified risks, their analysis, and treatment decisions." },
  { number: "6.1.1", title: "General", level: 2, parent: "6.1", description: "The organization shall plan actions to address risks and opportunities, and plan how to integrate and implement the actions into its ISMS processes and evaluate the effectiveness of these actions.", guidance: "Document your approach to risk management including criteria for risk acceptance, assessment methodology, and review frequency." },
  { number: "6.1.2", title: "Information Security Risk Assessment", level: 2, parent: "6.1", description: "The organization shall define and apply an information security risk assessment process that: establishes and maintains risk criteria including risk acceptance criteria and criteria for performing risk assessments; ensures that repeated risk assessments produce consistent, valid and comparable results; identifies information security risks (applying the risk assessment process to identify risks associated with the loss of confidentiality, integrity and availability); analyzes and evaluates the information security risks.", guidance: "Your risk assessment should: identify assets, threats, and vulnerabilities; assess likelihood and impact; calculate risk levels; compare against acceptance criteria. Use a consistent scale (e.g., 1-5 for likelihood and impact)." },
  { number: "6.1.3", title: "Information Security Risk Treatment", level: 2, parent: "6.1", description: "The organization shall define and apply an information security risk treatment process to: select appropriate risk treatment options; determine all controls necessary to implement the risk treatment options chosen; compare the controls with Annex A to verify no necessary controls have been omitted; produce a Statement of Applicability; formulate a risk treatment plan; obtain risk owners' approval of the risk treatment plan and acceptance of residual risks.", guidance: "For each risk above acceptance level, choose treatment: mitigate (apply controls), accept (with management approval), transfer (insurance/outsourcing), or avoid (eliminate the activity). Map selected controls to Annex A. The SoA must list all Annex A controls with justification for inclusion/exclusion." },
  { number: "6.2", title: "Information Security Objectives and Planning to Achieve Them", level: 1, parent: "6", description: "The organization shall establish information security objectives at relevant functions and levels. The objectives shall: be consistent with the information security policy; be measurable; take into account applicable requirements and risk assessment/treatment results; be monitored; be communicated; be updated as appropriate. Plans shall determine: what will be done; what resources will be required; who will be responsible; when it will be completed; how results will be evaluated.", guidance: "Set SMART objectives (Specific, Measurable, Achievable, Relevant, Time-bound). Examples: 'Reduce security incidents by 20% by year-end', 'Achieve 95% staff security awareness training completion by Q3', 'Complete risk assessment for all critical systems by Q2'." },
  { number: "6.3", title: "Planning of Changes", level: 1, parent: "6", description: "When the organization determines the need for changes to the ISMS, the changes shall be carried out in a planned manner.", guidance: "Establish a change management process for ISMS changes. Consider impact on existing controls, risk assessments, and documented information when making changes." },

  // Clause 7: Support
  { number: "7", title: "Support", level: 0, description: "Support covers the resources, competence, awareness, communication, and documented information needed to establish, implement, maintain, and continually improve the ISMS.", guidance: "This clause ensures you have everything needed to run the ISMS effectively. It covers people, knowledge, and documentation." },
  { number: "7.1", title: "Resources", level: 1, parent: "7", description: "The organization shall determine and provide the resources needed for the establishment, implementation, maintenance and continual improvement of the ISMS.", guidance: "Document budget allocations, personnel assignments, and technology resources dedicated to the ISMS. Ensure adequate staffing for security functions." },
  { number: "7.2", title: "Competence", level: 1, parent: "7", description: "The organization shall: determine the necessary competence of person(s) doing work under its control that affects information security performance; ensure that these persons are competent on the basis of appropriate education, training, or experience; where applicable, take actions to acquire the necessary competence and evaluate the effectiveness of the actions taken; retain appropriate documented information as evidence of competence.", guidance: "Maintain a training matrix showing required vs. actual competencies. Keep records of training certificates, qualifications, and experience. Conduct competency assessments for key security roles." },
  { number: "7.3", title: "Awareness", level: 1, parent: "7", description: "Persons doing work under the organization's control shall be aware of: the information security policy; their contribution to the effectiveness of the ISMS; the implications of not conforming with ISMS requirements.", guidance: "Implement a security awareness program including: induction training for new starters, regular refresher training, phishing simulations, and security communications. Track completion rates." },
  { number: "7.4", title: "Communication", level: 1, parent: "7", description: "The organization shall determine the need for internal and external communications relevant to the ISMS including: on what to communicate; when to communicate; with whom to communicate; how to communicate.", guidance: "Create a communication plan/matrix documenting: what security information is communicated, to whom, how often, and through what channels. Include incident reporting procedures and management reporting." },
  { number: "7.5", title: "Documented Information", level: 1, parent: "7", description: "The organization's ISMS shall include documented information required by ISO 27001 and documented information determined by the organization as necessary for the effectiveness of the ISMS. Documented information shall be controlled to ensure it is available and suitable for use, and adequately protected.", guidance: "Establish a document management system with version control, approval workflows, access controls, and retention policies. Key documents include: ISMS scope, policy, risk assessment methodology, risk treatment plan, SoA, and procedures." },

  // Clause 8: Operation
  { number: "8", title: "Operation", level: 0, description: "This clause covers the execution of plans and processes needed to meet information security requirements, including risk assessment and risk treatment.", guidance: "This is where you actually DO what you planned. Auditors look for evidence that plans from Clause 6 are being executed." },
  { number: "8.1", title: "Operational Planning and Control", level: 1, parent: "8", description: "The organization shall plan, implement and control the processes needed to meet information security requirements, and to implement the actions determined in 6.1. The organization shall also implement plans to achieve objectives determined in 6.2. The organization shall control planned changes and review the consequences of unintended changes, taking action to mitigate any adverse effects. The organization shall ensure that externally provided processes, products or services that are relevant to the ISMS are controlled.", guidance: "Implement the controls identified in risk treatment. Manage outsourced processes. Apply change management. Keep operational records and evidence." },
  { number: "8.2", title: "Information Security Risk Assessment", level: 1, parent: "8", description: "The organization shall perform information security risk assessments at planned intervals or when significant changes are proposed or occur, taking account of the criteria established in 6.1.2.", guidance: "Conduct risk assessments at least annually, and whenever significant changes occur (new systems, organizational changes, incidents). Document results and update the risk register." },
  { number: "8.3", title: "Information Security Risk Treatment", level: 1, parent: "8", description: "The organization shall implement the information security risk treatment plan. The organization shall retain documented information of the results of the information security risk treatment.", guidance: "Execute the risk treatment plan. Track implementation progress. Document residual risks and obtain management acceptance." },

  // Clause 9: Performance Evaluation
  { number: "9", title: "Performance Evaluation", level: 0, description: "This clause requires monitoring, measurement, analysis, evaluation, internal audit, and management review of the ISMS.", guidance: "You must demonstrate that the ISMS is effective through regular measurement and review. This clause provides the feedback loop for continual improvement." },
  { number: "9.1", title: "Monitoring, Measurement, Analysis and Evaluation", level: 1, parent: "9", description: "The organization shall determine: what needs to be monitored and measured, including information security processes and controls; the methods for monitoring, measurement, analysis and evaluation to ensure valid results; when the monitoring and measuring shall be performed; who shall monitor and measure; when the results shall be analyzed and evaluated; who shall analyze and evaluate these results.", guidance: "Define KPIs and metrics for your ISMS. Examples: number of incidents, patch compliance rate, training completion rate, risk assessment coverage. Report regularly to management." },
  { number: "9.2", title: "Internal Audit", level: 1, parent: "9", description: "The organization shall conduct internal audits at planned intervals to provide information on whether the ISMS: conforms to the organization's own requirements and the requirements of ISO 27001; is effectively implemented and maintained.", guidance: "Develop an internal audit program covering all ISMS requirements over a cycle. Auditors must be independent and competent. Document audit plans, findings, and corrective actions. Audit at least annually." },
  { number: "9.3", title: "Management Review", level: 1, parent: "9", description: "Top management shall review the organization's ISMS at planned intervals to ensure its continuing suitability, adequacy and effectiveness. The review shall include consideration of: status of actions from previous reviews; changes in external and internal issues; nonconformities and corrective actions; monitoring and measurement results; audit results; fulfilment of objectives; feedback from interested parties; results of risk assessment and status of risk treatment plan; opportunities for continual improvement.", guidance: "Conduct management reviews at least annually (many organizations do quarterly). Document meeting minutes including decisions and action items. Inputs must cover all items listed in the standard. Outputs must include decisions on improvement opportunities and changes to the ISMS." },

  // Clause 10: Improvement
  { number: "10", title: "Improvement", level: 0, description: "This clause requires the organization to continually improve the suitability, adequacy and effectiveness of the ISMS.", guidance: "Demonstrate a culture of improvement. Show how you learn from incidents, audits, and reviews to make the ISMS better over time." },
  { number: "10.1", title: "Continual Improvement", level: 1, parent: "10", description: "The organization shall continually improve the suitability, adequacy and effectiveness of the information security management system.", guidance: "Use the Plan-Do-Check-Act cycle. Document improvement initiatives and their outcomes. Show trending improvement in metrics over time." },
  { number: "10.2", title: "Nonconformity and Corrective Action", level: 1, parent: "10", description: "When a nonconformity occurs, the organization shall: react to the nonconformity and take action to control and correct it; evaluate the need for action to eliminate the causes of the nonconformity to prevent recurrence; implement any action needed; review the effectiveness of any corrective action taken; make changes to the ISMS if necessary.", guidance: "Establish a nonconformity and corrective action procedure. Use root cause analysis (e.g., 5 Whys). Track corrective actions to closure. Verify effectiveness. Maintain a corrective action register." }
];

const CONTROLS = [
  // A.5 Organizational Controls
  { number: "A.5.1", title: "Policies for information security", category: "Organizational", description: "A set of policies for information security shall be defined, approved by management, published and communicated to relevant personnel and relevant interested parties. The policies shall be reviewed at planned intervals or if significant changes occur to ensure their continuing suitability, adequacy and effectiveness.", guidance: "Create a policy hierarchy: top-level information security policy, topic-specific policies (access control, acceptable use, etc.), and supporting procedures. Ensure all policies are version-controlled, dated, and signed by appropriate management.", purpose: "To provide management direction and support for information security in accordance with business requirements and relevant laws and regulations." },
  { number: "A.5.2", title: "Information security roles and responsibilities", category: "Organizational", description: "Information security roles and responsibilities shall be defined and allocated. Conflicting duties and conflicting areas of responsibility shall be segregated.", guidance: "Define roles including CISO, security managers, system owners, data owners, users. Document in job descriptions and RACI matrices. Ensure segregation of duties where conflicts exist.", purpose: "To establish a defined and approved management framework to initiate and control the implementation and operation of information security within the organization." },
  { number: "A.5.3", title: "Segregation of duties", category: "Organizational", description: "Conflicting duties and conflicting areas of responsibility shall be segregated.", guidance: "Identify and separate conflicting roles (e.g., developer vs. deployer, requester vs. approver). Where segregation isn't possible, implement compensating controls like monitoring and logging.", purpose: "To reduce the risk of fraud, error and bypassing of information security controls." },
  { number: "A.5.4", title: "Management responsibilities", category: "Organizational", description: "Management shall require all personnel to apply information security in accordance with the established information security policy and topic-specific policies and procedures of the organization.", guidance: "Include security responsibilities in employment contracts. Ensure managers enforce compliance within their teams. Conduct regular security briefings.", purpose: "To ensure that management understands and fulfils their information security responsibilities." },
  { number: "A.5.5", title: "Contact with authorities", category: "Organizational", description: "The organization shall establish and maintain contact with relevant authorities.", guidance: "Maintain a contact list for: law enforcement, regulatory bodies, data protection authorities, emergency services, and CERTs/CSIRTs relevant to your jurisdiction.", purpose: "To ensure appropriate flow of information takes place with respect to information security between the organization and relevant legal, regulatory and supervisory authorities." },
  { number: "A.5.6", title: "Contact with special interest groups", category: "Organizational", description: "The organization shall establish and maintain contact with special interest groups or other specialist security forums and professional associations.", guidance: "Join industry groups, ISACs, security forums, and professional associations relevant to your sector. Subscribe to threat intelligence feeds and vulnerability databases.", purpose: "To ensure appropriate flow of information takes place with respect to information security." },
  { number: "A.5.7", title: "Threat intelligence", category: "Organizational", description: "Information relating to information security threats shall be collected and analysed to produce threat intelligence.", guidance: "This is new in 2022. Establish processes to collect, analyze, and act on threat intelligence from multiple sources. Categorize into strategic, tactical, and operational intelligence.", purpose: "To provide awareness of the organization's threat environment so that appropriate mitigation actions can be taken." },
  { number: "A.5.8", title: "Information security in project management", category: "Organizational", description: "Information security shall be integrated into project management.", guidance: "Include security requirements in project initiation. Conduct security reviews at project gates. Perform security testing before go-live. Apply to all projects, not just IT projects.", purpose: "To ensure that information security is integrated into project management throughout the project lifecycle." },
  { number: "A.5.9", title: "Inventory of information and other associated assets", category: "Organizational", description: "An inventory of information and other associated assets, including owners, shall be developed and maintained.", guidance: "Create and maintain an asset register covering: information assets, software, hardware, services, people, facilities. Assign owners. Classify assets. Review regularly.", purpose: "To identify the organization's information and other associated assets in order to preserve their information security and assign appropriate ownership." },
  { number: "A.5.10", title: "Acceptable use of information and other associated assets", category: "Organizational", description: "Rules for the acceptable use of information and other associated assets and information processing facilities shall be identified, documented and implemented.", guidance: "Create an acceptable use policy covering: internet use, email, mobile devices, social media, personal devices (BYOD), removable media. Communicate to all users and obtain acknowledgment.", purpose: "To ensure information and other associated assets are appropriately protected, used and handled." },
  { number: "A.5.11", title: "Return of assets", category: "Organizational", description: "Personnel and other interested parties as appropriate shall return all the organization's assets in their possession upon change or termination of their employment, contract or agreement.", guidance: "Include asset return in offboarding checklists. Track issued assets. Ensure return of: laptops, mobile devices, access cards, keys, documents, and revocation of digital access.", purpose: "To protect the organization's assets as part of the process of changing or terminating employment, contract or agreement." },
  { number: "A.5.12", title: "Classification of information", category: "Organizational", description: "Information shall be classified according to the information security needs of the organization based on confidentiality, integrity, availability and relevant interested party requirements.", guidance: "Define classification levels (e.g., Public, Internal, Confidential, Restricted). Create classification guidelines with examples. Label documents and systems accordingly.", purpose: "To ensure that information receives an appropriate level of protection in accordance with its importance to the organization." },
  { number: "A.5.13", title: "Labelling of information", category: "Organizational", description: "An appropriate set of procedures for information labelling shall be developed and implemented in accordance with the information classification scheme adopted by the organization.", guidance: "Define labelling rules for each classification level. Apply to physical and digital documents, emails, storage media. Automate where possible.", purpose: "To facilitate the communication of information classification and support automated processing." },
  { number: "A.5.14", title: "Information transfer", category: "Organizational", description: "Information transfer rules, procedures, or agreements shall be in place for all types of transfer facilities within the organization and between the organization and other parties.", guidance: "Define rules for transferring information: email, file sharing, physical transfer, electronic messaging. Include encryption requirements, authorization processes, and agreements with third parties.", purpose: "To maintain the security of information transferred within an organization and with any external interested party." },
  { number: "A.5.15", title: "Access control", category: "Organizational", description: "Rules to control physical and logical access to information and other associated assets shall be established and implemented based on business and information security requirements.", guidance: "Define access control policy based on least privilege and need-to-know. Cover both physical and logical access. Include rules for granting, reviewing, and revoking access.", purpose: "To ensure authorized access and to prevent unauthorized access to information and other associated assets." },
  { number: "A.5.16", title: "Identity management", category: "Organizational", description: "The full lifecycle of identities shall be managed.", guidance: "Implement identity lifecycle management: provisioning, maintenance, de-provisioning. Use unique identifiers. Manage service and shared accounts carefully. Regular identity reviews.", purpose: "To allow the unique identification of individuals and systems accessing the organization's information and other associated assets and to enable appropriate assignment of access rights." },
  { number: "A.5.17", title: "Authentication information", category: "Organizational", description: "Allocation and management of authentication information shall be controlled by a management process including advising personnel on appropriate handling of authentication information.", guidance: "Define password policies, implement MFA where appropriate, manage certificates and keys securely. Provide guidance on password management tools.", purpose: "To ensure proper entity authentication and to prevent failures of authentication processes." },
  { number: "A.5.18", title: "Access rights", category: "Organizational", description: "Access rights to information and other associated assets shall be provisioned, reviewed, modified and removed in accordance with the organization's topic-specific policy on and rules for access control.", guidance: "Implement formal access request and approval processes. Regular access reviews (quarterly minimum). Prompt revocation on role change or termination. Document all changes.", purpose: "To ensure that access to information and other associated assets is defined and authorized." },
  { number: "A.5.19", title: "Information security in supplier relationships", category: "Organizational", description: "Processes and procedures shall be defined and implemented to manage the information security risks associated with the use of supplier's products or services.", guidance: "Assess supplier security posture before engagement. Include security requirements in contracts. Monitor supplier compliance. Maintain supplier security register.", purpose: "To maintain an agreed level of information security in supplier relationships." },
  { number: "A.5.20", title: "Addressing information security within supplier agreements", category: "Organizational", description: "Relevant information security requirements shall be established and agreed with each supplier based on the type of supplier relationship.", guidance: "Include in contracts: security requirements, right to audit, incident notification, data handling, sub-contractor management, termination provisions. Use standard clauses adapted to risk level.", purpose: "To maintain an agreed level of information security in supplier relationships." },
  { number: "A.5.21", title: "Managing information security in the ICT supply chain", category: "Organizational", description: "Processes and procedures shall be defined and implemented to manage the information security risks associated with the ICT products and services supply chain.", guidance: "New in 2022. Assess supply chain risks for ICT products and services. Include security requirements for suppliers' suppliers. Monitor for supply chain compromises.", purpose: "To maintain an agreed level of information security in supplier relationships in relation to the ICT supply chain." },
  { number: "A.5.22", title: "Monitoring, review and change management of supplier services", category: "Organizational", description: "The organization shall regularly monitor, review, evaluate and manage change in supplier information security practices and service delivery.", guidance: "Conduct regular supplier reviews. Monitor SLA compliance. Assess impact of supplier changes. Include security in vendor management processes.", purpose: "To maintain an agreed level of information security and service delivery in line with supplier agreements." },
  { number: "A.5.23", title: "Information security for use of cloud services", category: "Organizational", description: "Processes for acquisition, use, management and exit from cloud services shall be established in accordance with the organization's information security requirements.", guidance: "New in 2022. Define cloud security policy. Assess cloud provider security. Manage shared responsibility model. Plan for cloud service termination or migration.", purpose: "To specify and manage information security for the use of cloud services." },
  { number: "A.5.24", title: "Information security incident management planning and preparation", category: "Organizational", description: "The organization shall plan and prepare for managing information security incidents by defining, establishing and communicating information security incident management processes, roles and responsibilities.", guidance: "Create incident response plan. Define roles (incident commander, responders, communicators). Establish escalation procedures. Test the plan regularly.", purpose: "To ensure a quick, effective and orderly response to information security incidents." },
  { number: "A.5.25", title: "Assessment and decision on information security events", category: "Organizational", description: "The organization shall assess information security events and decide if they are to be categorized as information security incidents.", guidance: "Define criteria for classifying events vs incidents. Establish triage process. Document classification decisions. Use severity levels.", purpose: "To ensure that information security events are adequately assessed and classified." },
  { number: "A.5.26", title: "Response to information security incidents", category: "Organizational", description: "Information security incidents shall be responded to in accordance with the documented procedures.", guidance: "Follow incident response procedures. Document actions taken. Preserve evidence. Coordinate with relevant parties. Communicate status updates.", purpose: "To ensure that information security incidents are responded to appropriately." },
  { number: "A.5.27", title: "Learning from information security incidents", category: "Organizational", description: "Knowledge gained from information security incidents shall be used to strengthen and improve the information security controls.", guidance: "Conduct post-incident reviews. Document lessons learned. Update risk assessments and controls. Share knowledge across the organization.", purpose: "To reduce the likelihood or consequences of future incidents." },
  { number: "A.5.28", title: "Collection of evidence", category: "Organizational", description: "The organization shall establish and implement procedures for the identification, collection, acquisition and preservation of evidence related to information security events.", guidance: "Define evidence handling procedures following forensic best practices. Maintain chain of custody. Preserve digital evidence integrity. Consider legal admissibility requirements.", purpose: "To ensure proper evidence management for potential legal or disciplinary actions." },
  { number: "A.5.29", title: "Information security during disruption", category: "Organizational", description: "The organization shall plan how to maintain information security at an appropriate level during disruption.", guidance: "Include security in business continuity plans. Define minimum security levels during disruption. Plan for degraded operations while maintaining security.", purpose: "To protect information and other associated assets during disruption." },
  { number: "A.5.30", title: "ICT readiness for business continuity", category: "Organizational", description: "ICT readiness shall be planned, implemented, maintained and tested based on business continuity objectives and ICT continuity requirements.", guidance: "New in 2022. Define RTOs and RPOs for critical ICT services. Implement redundancy and failover. Test recovery procedures regularly. Document recovery plans.", purpose: "To ensure the availability of ICT services to support business operations." },
  { number: "A.5.31", title: "Legal, statutory, regulatory and contractual requirements", category: "Organizational", description: "Legal, statutory, regulatory and contractual requirements relevant to information security and the organization's approach to meet these requirements shall be identified, documented and kept up to date.", guidance: "Maintain a legal register. Include data protection laws, industry regulations, contractual obligations. Review regularly for changes. Assign compliance responsibilities.", purpose: "To ensure compliance with legal, statutory, regulatory and contractual requirements related to information security." },
  { number: "A.5.32", title: "Intellectual property rights", category: "Organizational", description: "The organization shall implement appropriate procedures to protect intellectual property rights.", guidance: "Track software licenses. Protect proprietary information. Ensure compliance with copyright and license terms. Include IP protection in employment agreements.", purpose: "To ensure compliance with legal, statutory, regulatory and contractual requirements related to intellectual property rights." },
  { number: "A.5.33", title: "Protection of records", category: "Organizational", description: "Records shall be protected from loss, destruction, falsification, unauthorized access and unauthorized release in accordance with legislative, regulatory, contractual and business requirements.", guidance: "Define record retention periods. Implement secure storage. Ensure record integrity. Apply appropriate access controls. Plan for secure disposal.", purpose: "To ensure compliance with legal, statutory, regulatory and contractual requirements, as well as community or societal expectations related to the protection and availability of records." },
  { number: "A.5.34", title: "Privacy and protection of personal information", category: "Organizational", description: "The organization shall identify and meet the requirements regarding the preservation of privacy and protection of PII as required in applicable legislation and regulation and contractual requirements.", guidance: "Identify PII processed. Conduct privacy impact assessments. Implement privacy by design. Comply with GDPR/applicable data protection laws. Appoint DPO if required.", purpose: "To ensure compliance with legal, statutory, regulatory and contractual requirements related to information privacy." },
  { number: "A.5.35", title: "Independent review of information security", category: "Organizational", description: "The organization's approach to managing information security and its implementation including people, processes and technologies shall be reviewed independently at planned intervals, or when significant changes occur.", guidance: "Conduct independent security reviews/audits at least annually. Include penetration testing. Review by qualified internal or external auditors. Act on findings.", purpose: "To ensure the continuing suitability, adequacy and effectiveness of the organization's approach to managing information security." },
  { number: "A.5.36", title: "Compliance with policies, rules and standards for information security", category: "Organizational", description: "Compliance with the organization's established information security policy, topic-specific policies, rules and standards shall be regularly reviewed.", guidance: "Conduct regular compliance checks. Monitor policy adherence. Review and report on compliance status. Address non-compliance through corrective actions.", purpose: "To ensure that information security is implemented and operated in accordance with the organization's information security policy." },
  { number: "A.5.37", title: "Documented operating procedures", category: "Organizational", description: "Operating procedures for information processing facilities shall be documented and made available to personnel who need them.", guidance: "Document procedures for: system operations, backup, monitoring, incident handling, change management. Keep procedures current and accessible.", purpose: "To ensure the correct and secure operation of information processing facilities." },

  // A.6 People Controls
  { number: "A.6.1", title: "Screening", category: "People", description: "Background verification checks on all candidates to become personnel shall be carried out prior to joining the organization and on an ongoing basis taking into consideration applicable laws, regulations and ethics, and be proportional to the business requirements, the classification of the information to be accessed and the perceived risks.", guidance: "Conduct background checks appropriate to role sensitivity: identity verification, reference checks, qualification verification, criminal record checks (where legal). Define screening levels by role classification.", purpose: "To ensure that all personnel are eligible and suitable for the roles for which they are considered and remain eligible and suitable during their employment." },
  { number: "A.6.2", title: "Terms and conditions of employment", category: "People", description: "The employment contractual agreements shall state the personnel's and the organization's responsibilities for information security.", guidance: "Include in contracts: confidentiality clauses, security responsibilities, acceptable use acknowledgment, IP assignment, post-employment obligations. Get signed acknowledgment.", purpose: "To ensure that personnel understand and fulfil their information security responsibilities." },
  { number: "A.6.3", title: "Information security awareness, education and training", category: "People", description: "Personnel of the organization and relevant interested parties shall receive appropriate information security awareness education and training and regular updates of the organization's information security policy, topic-specific policies and procedures, as relevant for their job function.", guidance: "Implement comprehensive awareness program: onboarding training, annual refreshers, role-specific training, phishing simulations, security newsletters. Track and report completion.", purpose: "To ensure that personnel and relevant interested parties are aware of and fulfil their information security responsibilities." },
  { number: "A.6.4", title: "Disciplinary process", category: "People", description: "A disciplinary process shall be formalized and communicated to take actions against personnel and other relevant interested parties who have committed an information security policy violation.", guidance: "Define disciplinary procedures for security violations. Ensure consistency and fairness. Include in employee handbook. Consider graduated responses based on severity.", purpose: "To ensure that personnel and other relevant interested parties understand the consequences of information security policy violation." },
  { number: "A.6.5", title: "Responsibilities after termination or change of employment", category: "People", description: "Information security responsibilities and duties that remain valid after termination or change of employment shall be defined, enforced and communicated to relevant personnel and other interested parties.", guidance: "Define post-employment obligations: NDAs, return of assets, knowledge transfer. Communicate during offboarding. Include in employment contracts.", purpose: "To protect the organization's interests as part of the process of changing or terminating employment." },
  { number: "A.6.6", title: "Confidentiality or non-disclosure agreements", category: "People", description: "Confidentiality or non-disclosure agreements reflecting the organization's needs for the protection of information shall be identified, documented, regularly reviewed and signed by personnel and other relevant interested parties.", guidance: "Require NDAs for employees, contractors, and third parties. Review and update NDAs regularly. Ensure they cover all relevant information. Maintain signed copies.", purpose: "To maintain confidentiality of information accessible by personnel or external parties." },
  { number: "A.6.7", title: "Remote working", category: "People", description: "Security measures shall be implemented when personnel are working remotely to protect information accessed, processed or stored outside the organization's premises.", guidance: "New in 2022. Define remote working policy. Require VPN, encrypt devices, secure home networks. Address physical security of remote workspaces. Define acceptable locations.", purpose: "To ensure the security of information when personnel are working remotely." },
  { number: "A.6.8", title: "Information security event reporting", category: "People", description: "The organization shall provide a mechanism for personnel to report observed or suspected information security events through appropriate channels in a timely manner.", guidance: "Establish clear reporting channels (hotline, email, ticketing system). Make reporting easy and accessible. Encourage reporting without fear of blame. Acknowledge reports promptly.", purpose: "To support timely, consistent, and effective reporting of information security events that can be identified by personnel." },

  // A.7 Physical Controls
  { number: "A.7.1", title: "Physical security perimeters", category: "Physical", description: "Security perimeters shall be defined and used to protect areas that contain information and other associated assets.", guidance: "Define physical security zones. Implement barriers, walls, locked doors. Use reception areas. Separate public and secure areas. Consider datacentre security tiers.", purpose: "To prevent unauthorized physical access, damage and interference to the organization's information and other associated assets." },
  { number: "A.7.2", title: "Physical entry", category: "Physical", description: "Secure areas shall be protected by appropriate entry controls and access points.", guidance: "Implement access control systems (cards, biometrics). Visitor management procedures. Entry logging. Escort requirements for visitors. Regular access review.", purpose: "To ensure only authorized access to secure areas." },
  { number: "A.7.3", title: "Securing offices, rooms and facilities", category: "Physical", description: "Physical security for offices, rooms and facilities shall be designed and implemented.", guidance: "Lock offices containing sensitive information. Secure server rooms with additional controls. Apply clean desk policy. Secure printing facilities.", purpose: "To prevent unauthorized physical access, damage and interference to the organization's information and other associated assets in offices, rooms and facilities." },
  { number: "A.7.4", title: "Physical security monitoring", category: "Physical", description: "Premises shall be continuously monitored for unauthorized physical access.", guidance: "New in 2022. Implement CCTV, intrusion detection, security patrols. Monitor 24/7. Maintain recordings for appropriate retention period. Review incidents promptly.", purpose: "To detect and deter unauthorized physical access." },
  { number: "A.7.5", title: "Protecting against physical and environmental threats", category: "Physical", description: "Protection against physical and environmental threats, such as natural disasters and other intentional or unintentional physical threats to infrastructure shall be designed and implemented.", guidance: "Assess environmental risks (flood, fire, earthquake). Implement fire suppression, UPS, generators, climate control. Locate critical systems away from high-risk areas.", purpose: "To prevent or reduce the consequences of events originating from physical and environmental threats." },
  { number: "A.7.6", title: "Working in secure areas", category: "Physical", description: "Security measures for working in secure areas shall be designed and implemented.", guidance: "Define rules for secure areas: no unauthorized photography, no lone working where inappropriate, supervise third-party access. Lock areas when unoccupied.", purpose: "To protect information and other associated assets in secure areas from damage and unauthorized interference by personnel working in those areas." },
  { number: "A.7.7", title: "Clear desk and clear screen", category: "Physical", description: "Clear desk rules for papers and removable storage media and clear screen rules for information processing facilities shall be defined and appropriately enforced.", guidance: "Implement clear desk policy: lock away papers and media, lock screens when away, secure printers. Conduct spot checks. Provide lockable storage.", purpose: "To reduce the risks of unauthorized access, loss of and damage to information on desks, screens and in other accessible locations during and outside normal working hours." },
  { number: "A.7.8", title: "Equipment siting and protection", category: "Physical", description: "Equipment shall be sited securely and protected.", guidance: "Position screens away from windows. Protect equipment from environmental hazards. Secure cabling. Consider electromagnetic interference. Lock down portable equipment.", purpose: "To reduce the risks from physical and environmental threats, and from unauthorized access and damage." },
  { number: "A.7.9", title: "Security of assets off-premises", category: "Physical", description: "Off-site assets shall be protected.", guidance: "Define rules for equipment taken off-site. Encrypt portable devices. Track off-site assets. Include in insurance coverage. Define reporting procedures for loss.", purpose: "To prevent loss, damage, theft or compromise of off-site devices and interruption to the organization's operations." },
  { number: "A.7.10", title: "Storage media", category: "Physical", description: "Storage media shall be managed through their life cycle of acquisition, use, transportation and disposal in accordance with the organization's classification scheme and handling requirements.", guidance: "Control media throughout lifecycle. Encrypt sensitive media. Secure transportation. Implement secure disposal (degaussing, destruction). Maintain disposal records.", purpose: "To ensure that information on storage media is not disclosed, modified, removed or destroyed in an unauthorized manner." },
  { number: "A.7.11", title: "Supporting utilities", category: "Physical", description: "Information processing facilities shall be protected from power failures and other disruptions caused by failures in supporting utilities.", guidance: "Implement UPS, backup generators, redundant cooling. Test regularly. Maintain service agreements. Monitor environmental conditions.", purpose: "To prevent loss, damage or compromise of information and other associated assets, or interruption to the organization's operations due to the failure and disruption of supporting utilities." },
  { number: "A.7.12", title: "Cabling security", category: "Physical", description: "Cables carrying power, data or supporting information services shall be protected from interception, interference or damage.", guidance: "Protect network and power cabling. Use conduits. Separate power and data cables. Secure patch panels and distribution points. Label cables appropriately.", purpose: "To prevent loss, damage, theft or compromise of information and other associated assets and interruption to the organization's operations related to power and communications cabling." },
  { number: "A.7.13", title: "Equipment maintenance", category: "Physical", description: "Equipment shall be maintained correctly to ensure availability, integrity and confidentiality of information.", guidance: "Follow manufacturer maintenance schedules. Use authorized service personnel. Clear sensitive data before sending equipment for repair. Log all maintenance activities.", purpose: "To prevent loss, damage, theft or compromise of information and other associated assets and interruption to the organization's operations caused by lack of maintenance." },
  { number: "A.7.14", title: "Secure disposal or re-use of equipment", category: "Physical", description: "Items of equipment containing storage media shall be verified to ensure that any sensitive data and licensed software has been removed or securely overwritten prior to disposal or re-use.", guidance: "Sanitize all storage media before disposal or reuse. Use certified destruction services. Maintain disposal records. Verify sanitization effectiveness.", purpose: "To prevent leakage of information from equipment to be disposed of or re-used." },

  // A.8 Technological Controls
  { number: "A.8.1", title: "User endpoint devices", category: "Technological", description: "Information stored on, processed by or accessible via user endpoint devices shall be protected.", guidance: "Implement endpoint security: encryption, anti-malware, patch management, screen lock, remote wipe capability. Define BYOD policy. Manage device configurations.", purpose: "To protect information against the risks introduced by using user endpoint devices." },
  { number: "A.8.2", title: "Privileged access rights", category: "Technological", description: "The allocation and use of privileged access rights shall be restricted and managed.", guidance: "Implement PAM (Privileged Access Management). Use separate admin accounts. Time-limit privileged sessions. Log all privileged actions. Review quarterly.", purpose: "To ensure only authorized users, software components and services are provided with privileged access rights." },
  { number: "A.8.3", title: "Information access restriction", category: "Technological", description: "Access to information and other associated assets shall be restricted in accordance with the established topic-specific policy on access control.", guidance: "Implement role-based access control. Restrict access to sensitive data. Apply data masking where appropriate. Control access at application and database levels.", purpose: "To ensure only authorized access to information and other associated assets." },
  { number: "A.8.4", title: "Access to source code", category: "Technological", description: "Read and write access to source code, development tools and software libraries shall be appropriately managed.", guidance: "Restrict access to source code repositories. Use version control with access controls. Review access regularly. Protect against unauthorized modifications.", purpose: "To prevent introduction of unauthorized functionality, avoid unintentional or deliberate modifications and maintain the confidentiality of valuable intellectual property." },
  { number: "A.8.5", title: "Secure authentication", category: "Technological", description: "Secure authentication technologies and procedures shall be established and implemented based on information access restrictions and the topic-specific policy on access control.", guidance: "Implement MFA for critical systems and remote access. Use strong password policies. Protect authentication mechanisms. Monitor authentication failures.", purpose: "To ensure a user or an entity is securely authenticated when access to systems, applications and services is granted." },
  { number: "A.8.6", title: "Capacity management", category: "Technological", description: "The use of resources shall be monitored and adjusted in line with current and expected capacity requirements.", guidance: "Monitor system capacity (CPU, memory, storage, bandwidth). Plan for growth. Set alerts for capacity thresholds. Document capacity plans.", purpose: "To ensure the required capacity of information processing facilities, human resources, offices and other facilities." },
  { number: "A.8.7", title: "Protection against malware", category: "Technological", description: "Protection against malware shall be implemented and supported by appropriate user awareness.", guidance: "Deploy anti-malware on all endpoints and servers. Keep signatures updated. Implement email filtering. Conduct user awareness on malware risks. Monitor for malware events.", purpose: "To ensure that information and other associated assets are protected against malware." },
  { number: "A.8.8", title: "Management of technical vulnerabilities", category: "Technological", description: "Information about technical vulnerabilities of information systems in use shall be obtained, the organization's exposure to such vulnerabilities shall be evaluated and appropriate measures shall be taken.", guidance: "Implement vulnerability management program: regular scanning, patch management, vulnerability assessment. Define patching timelines by severity. Track remediation.", purpose: "To prevent exploitation of technical vulnerabilities." },
  { number: "A.8.9", title: "Configuration management", category: "Technological", description: "Configurations, including security configurations, of hardware, software, services and networks shall be established, documented, implemented, monitored and reviewed.", guidance: "New in 2022. Define security baselines for systems. Implement configuration management tools. Monitor for configuration drift. Review and harden configurations.", purpose: "To ensure hardware, software, services and networks function correctly with required security settings, and configuration is not altered by unauthorized or incorrect changes." },
  { number: "A.8.10", title: "Information deletion", category: "Technological", description: "Information stored in information systems, devices or in any other storage media shall be deleted when no longer required.", guidance: "New in 2022. Define retention periods. Implement automated deletion where possible. Verify deletion effectiveness. Consider legal hold requirements.", purpose: "To prevent unnecessary exposure of sensitive information and to comply with legal, statutory, regulatory and contractual requirements for information deletion." },
  { number: "A.8.11", title: "Data masking", category: "Technological", description: "Data masking shall be used in accordance with the organization's topic-specific policy on access control and other related topic-specific policies, and business requirements, taking applicable legislation into consideration.", guidance: "New in 2022. Identify data requiring masking. Implement masking techniques (anonymization, pseudonymization, tokenization). Use in test environments and for access restriction.", purpose: "To limit the exposure of sensitive data including PII, and to comply with legal, statutory, regulatory and contractual requirements." },
  { number: "A.8.12", title: "Data leakage prevention", category: "Technological", description: "Data leakage prevention measures shall be applied to systems, networks and any other devices that process, store or transmit sensitive information.", guidance: "New in 2022. Implement DLP tools. Monitor data exfiltration channels. Define rules for sensitive data handling. Block unauthorized transfers. Alert on policy violations.", purpose: "To detect and prevent the unauthorized disclosure and extraction of information by individuals or systems." },
  { number: "A.8.13", title: "Information backup", category: "Technological", description: "Backup copies of information, software and systems shall be maintained and regularly tested in accordance with the agreed topic-specific policy on backup.", guidance: "Define backup policy covering: frequency, retention, scope, testing. Implement automated backups. Test restores regularly. Store backups off-site/off-line. Encrypt backup data.", purpose: "To allow recovery of information and other associated assets following data loss, or system or service interruption." },
  { number: "A.8.14", title: "Redundancy of information processing facilities", category: "Technological", description: "Information processing facilities shall be implemented with sufficient redundancy to meet availability requirements.", guidance: "Implement redundancy for critical systems: clustering, load balancing, failover. Define and test failover procedures. Consider geographic redundancy.", purpose: "To ensure the continuous operation of information processing facilities." },
  { number: "A.8.15", title: "Logging", category: "Technological", description: "Logs that record activities, exceptions, faults and other relevant events shall be produced, stored, protected and analysed.", guidance: "Log security events: access attempts, privilege use, system changes, errors. Protect log integrity. Set retention periods. Implement centralized logging (SIEM). Regular review.", purpose: "To record events, generate evidence, ensure the integrity of log information and protect log data against unauthorized changes." },
  { number: "A.8.16", title: "Monitoring activities", category: "Technological", description: "Networks, systems and applications shall be monitored for anomalous behaviour and appropriate actions taken to evaluate potential information security incidents.", guidance: "New in 2022. Implement monitoring for: network traffic, system behavior, application activity, user behavior. Define anomaly detection rules. Establish alerting and response procedures.", purpose: "To detect anomalous behaviour and potential information security incidents." },
  { number: "A.8.17", title: "Clock synchronization", category: "Technological", description: "The clocks of information processing systems used by the organization shall be synchronized to approved time sources.", guidance: "Use NTP to synchronize all systems. Define authoritative time source. Monitor synchronization status. Essential for log correlation and forensics.", purpose: "To enable the correlation and analysis of security-related events and other recorded data, and to support investigations of information security incidents." },
  { number: "A.8.18", title: "Use of privileged utility programs", category: "Technological", description: "The use of utility programs that can be capable of overriding system and application controls shall be restricted and tightly controlled.", guidance: "Identify privileged utilities. Restrict access. Remove unnecessary utilities. Log usage. Implement application whitelisting where appropriate.", purpose: "To ensure the use of utility programs does not harm system or application controls." },
  { number: "A.8.19", title: "Installation of software on operational systems", category: "Technological", description: "Procedures and measures shall be implemented to securely manage software installation on operational systems.", guidance: "Control software installation: approval process, authorized sources only, application whitelisting. Monitor for unauthorized installations. Maintain software inventory.", purpose: "To ensure the integrity of operational systems and to prevent exploitation of technical vulnerabilities." },
  { number: "A.8.20", title: "Networks security", category: "Technological", description: "Networks and network devices shall be secured, managed and controlled to protect information in systems and applications.", guidance: "Implement network security: firewalls, IDS/IPS, network segmentation, secure configuration of network devices. Monitor network traffic. Regular security assessments.", purpose: "To protect information in systems and applications from being compromised through the network." },
  { number: "A.8.21", title: "Security of network services", category: "Technological", description: "Security mechanisms, service levels and service requirements of network services shall be identified, implemented and monitored.", guidance: "Define security requirements for network services. Include in SLAs with providers. Monitor service security. Implement secure protocols (TLS, VPN).", purpose: "To ensure security in the use of network services." },
  { number: "A.8.22", title: "Segregation of networks", category: "Technological", description: "Groups of information services, users and information systems shall be segregated in the organization's networks.", guidance: "Segment networks by security zone (DMZ, internal, guest). Use VLANs and firewalls. Restrict cross-zone traffic. Isolate sensitive systems.", purpose: "To divide the network into security domains and control traffic between them based on business needs." },
  { number: "A.8.23", title: "Web filtering", category: "Technological", description: "Access to external websites shall be managed to reduce exposure to malicious content.", guidance: "New in 2022. Implement web content filtering. Block known malicious sites. Control access to risky categories. Monitor web usage. Update filter lists regularly.", purpose: "To protect systems from being compromised by malware and to prevent access to unauthorized web resources." },
  { number: "A.8.24", title: "Use of cryptography", category: "Technological", description: "Rules for the effective use of cryptography, including cryptographic key management, shall be defined and implemented.", guidance: "Define cryptography policy covering: algorithms, key lengths, key management lifecycle, use cases (encryption at rest, in transit, hashing). Follow industry standards.", purpose: "To ensure proper and effective use of cryptography to protect the confidentiality, authenticity and/or integrity of information." },
  { number: "A.8.25", title: "Secure development life cycle", category: "Technological", description: "Rules for the secure development of software and systems shall be established and applied.", guidance: "Implement SDLC security practices: security requirements, threat modeling, secure coding guidelines, code review, security testing. Train developers.", purpose: "To ensure that information security is designed and implemented within the secure development life cycle of software and systems." },
  { number: "A.8.26", title: "Application security requirements", category: "Technological", description: "Information security requirements shall be identified, specified and approved when developing or acquiring applications.", guidance: "Define security requirements for applications: authentication, authorization, input validation, encryption, logging, error handling. Include in specifications.", purpose: "To ensure that all information security requirements are identified and addressed when developing or acquiring applications." },
  { number: "A.8.27", title: "Secure system architecture and engineering principles", category: "Technological", description: "Principles for engineering secure systems shall be established, documented, maintained and applied to any information system development activities.", guidance: "Define secure architecture principles: defense in depth, least privilege, fail secure, separation of concerns. Apply to all system designs. Review architecture for security.", purpose: "To ensure information systems are securely designed and that security is considered throughout the system development lifecycle." },
  { number: "A.8.28", title: "Secure coding", category: "Technological", description: "Secure coding principles shall be applied to software development.", guidance: "New in 2022. Define secure coding standards. Address OWASP Top 10. Implement automated code analysis. Conduct code reviews. Use secure frameworks and libraries.", purpose: "To ensure that software is written securely thereby reducing the number of potential information security vulnerabilities in the software." },
  { number: "A.8.29", title: "Security testing in development and acceptance", category: "Technological", description: "Security testing processes shall be defined and implemented in the development life cycle.", guidance: "Include in SDLC: SAST, DAST, penetration testing, vulnerability scanning. Define acceptance criteria. Test before deployment. Document results.", purpose: "To validate that information security requirements are met when applications or code are deployed to the production environment." },
  { number: "A.8.30", title: "Outsourced development", category: "Technological", description: "The organization shall direct, monitor and review the activities related to outsourced system development.", guidance: "Include security requirements in development contracts. Review security of outsourced code. Conduct security testing. Protect IP. Monitor development activities.", purpose: "To ensure that information security measures required by the organization are implemented in outsourced system development." },
  { number: "A.8.31", title: "Separation of development, test and production environments", category: "Technological", description: "Development, testing and production environments shall be separated and secured.", guidance: "Separate environments with appropriate controls. Restrict production access. Do not use production data in test environments without sanitization. Control deployments.", purpose: "To reduce the risks of unauthorized access or changes to the production environment." },
  { number: "A.8.32", title: "Change management", category: "Technological", description: "Changes to information processing facilities and information systems shall be subject to change management procedures.", guidance: "Implement formal change management: request, assessment, approval, testing, implementation, review. Categorize changes by risk. Emergency change procedures.", purpose: "To preserve information security when executing changes in information processing facilities and systems." },
  { number: "A.8.33", title: "Test information", category: "Technological", description: "Test information shall be appropriately selected, protected and managed.", guidance: "Protect test data. Do not use real PII in test environments. Anonymize/pseudonymize production data used for testing. Control access to test data.", purpose: "To ensure the relevance of testing and to protect the confidentiality of information used for testing." },
  { number: "A.8.34", title: "Protection of information systems during audit testing", category: "Technological", description: "Audit tests and other assurance activities involving assessment of operational systems shall be planned and agreed between the tester and appropriate management.", guidance: "Plan audit activities carefully. Minimize impact on production. Protect audit tools and results. Restrict access to audit test results. Coordinate timing.", purpose: "To minimize the impact of audit and other assurance activities on operational systems and business processes." }
];

async function main() {
  console.log('Seeding ISO 27001:2022 data...');

  // Create clauses
  const clauseMap = {};
  for (const c of CLAUSES) {
    const data = {
      number: c.number,
      title: c.title,
      description: c.description,
      guidance: c.guidance || null,
      level: c.level
    };
    if (c.parent && clauseMap[c.parent]) {
      data.parentId = clauseMap[c.parent].id;
    }
    const created = await prisma.clause.upsert({
      where: { number: c.number },
      update: data,
      create: data
    });
    clauseMap[c.number] = created;
    console.log(`  Clause ${c.number}: ${c.title}`);
  }

  // Create controls
  for (const ctrl of CONTROLS) {
    await prisma.control.upsert({
      where: { number: ctrl.number },
      update: {
        title: ctrl.title,
        description: ctrl.description,
        guidance: ctrl.guidance || null,
        category: ctrl.category,
        purpose: ctrl.purpose || null
      },
      create: {
        number: ctrl.number,
        title: ctrl.title,
        description: ctrl.description,
        guidance: ctrl.guidance || null,
        category: ctrl.category,
        purpose: ctrl.purpose || null
      }
    });
    console.log(`  Control ${ctrl.number}: ${ctrl.title}`);
  }

  console.log(`\nSeeded ${CLAUSES.length} clauses and ${CONTROLS.length} Annex A controls.`);
}

main()
  .catch(e => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
